# Generated by Django 4.1.7 on 2023-05-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_nkustnews"),
    ]

    operations = [
        migrations.CreateModel(
            name="alldata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                ("season", models.CharField(max_length=255)),
                ("area", models.CharField(max_length=255)),
                (
                    "self_avg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "industry_avg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="nkustnews",
        ),
    ]
