# Generated by Django 4.1.7 on 2023-06-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0003_alldata_delete_nkustnews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alldata",
            name="area",
            field=models.CharField(
                choices=[
                    ("North", "北部"),
                    ("Middle", "中部"),
                    ("South", "南部"),
                    ("East", "東部"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="alldata",
            name="season",
            field=models.CharField(
                choices=[
                    ("Spring", "春"),
                    ("Summer", "夏"),
                    ("Autumn", "秋"),
                    ("Winter", "冬"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="alldata",
            name="year",
            field=models.CharField(
                choices=[
                    (2019, "2019年"),
                    (2020, "2020年"),
                    (2021, "2021年"),
                    (2022, "2022年"),
                ],
                max_length=255,
            ),
        ),
    ]
