# Generated by Django 4.1 on 2023-11-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0004_alter_alldata_area_alter_alldata_season_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="enddate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=255)),
                ("month", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="GHtrashData",
        ),
        migrations.AlterField(
            model_name="alldata",
            name="year",
            field=models.CharField(
                choices=[
                    ("2019", "2019年"),
                    ("2020", "2020年"),
                    ("2021", "2021年"),
                    ("2022", "2022年"),
                    ("2023", "2023年"),
                ],
                max_length=255,
            ),
        ),
    ]
